Import('env')
testenv = env.Clone()
SRC = [
   'src/TestBasicStubbing.cpp',
   'src/TestDefaultAction.cpp',
   'src/TestIterator.cpp',
   'src/TestSimpleComposite.cpp',
   'src/TestVerify.cpp'
]
testenv.AppendUnique(CPPPATH = ['#cpp'])
testenv.AppendUnique(CPPPATH = ['#3rdparty/boost_headers_1_36_0'])
testenv.AppendUnique(CPPPATH = ['#3rdparty/googletest-1.1.0/include'])
testenv.AppendUnique(LIBPATH = '#3rdparty/build')
testenv.AppendUnique(LIBS = 'googletest')
test = testenv.Program('test', SRC)
unitTest = testenv.Test('test')

# vim:ft=python:
