Import('env')
testenv = env.Clone()
TEST_SRC = [
   # TODO: deprecate
   'src/TestArguments.cpp',
   'src/TestBasicStubbing.cpp',
#   'src/TestDefaultAction.cpp',
   'src/TestSimpleComposite.cpp',

   'src/test_iterator_style.cpp',
   'src/test_verify.cpp',
   'src/matchers/test_any.cpp',
   'src/matchers/test_custom.cpp',
   'src/matchers/test_equal.cpp',
   'src/matchers/test_hamcrest.cpp',
   'src/matchers/test_is_not.cpp',
   'src/matchers/test_null.cpp',
   'src/matchers/test_string_literal.cpp',
   'src/matchers/test_tr1_regex.cpp',
]
testenv.AppendUnique(CPPPATH = ['#include'])
testenv.AppendUnique(CPPPATH = ['#3rdparty/boost_1_36_0/include'])
testenv.AppendUnique(CPPPATH = ['#3rdparty/googletest-1.2.1/include'])
testenv.AppendUnique(CPPPATH = ['#3rdparty/hamcrest-r389/core'])
testenv.AppendUnique(LIBPATH = ['#3rdparty/build'])
testenv.AppendUnique(LIBS = ['boost-regex'])
testenv.AppendUnique(LIBS = ['googletest'])
testenv.AppendUnique(LIBS = ['hamcrest'])
test = testenv.Program('test', TEST_SRC)
unitTest = testenv.Test('test')

# vim:ft=python:
