name: Build
on: push
jobs:
   build:
      runs-on: ${{ matrix.os }}
      strategy:
         fail-fast: false
         matrix:
            cxx:
               - clang++
               - cl.exe
               - g++
            include:
               - os: ubuntu-18.04
                 cxx: clang++
                 run: "true"
               - os: ubuntu-18.04
                 cxx: g++
                 run: "true"
               - os: windows-2019
                 cxx: cl.exe
                 run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"'
      name: ${{ matrix.os }} - ${{ matrix.cxx }}
      steps:
         - uses: actions/checkout@v1
         - uses: actions/setup-python@v1
           with:
              python-version: 2.x
         - run: pip install scons
         - run: ${{ matrix.run }}
         - run: scons
           env:
              CXX: ${{ matrix.cxx }}
